### ISSUE TITLE
Error on launch and no output

### ISSUE THREAD

**Issue by vassilmladenov** [whitequark/Sublime-Coq#6]
I get the following error dialog when I run "Coq: Start".

> Error loading syntax file "Packages/Sublime-Coq/Coq Toplevel.sublime-syntax": Unable to read Packages/Sublime-Coq/Coq Toplevel.sublime-syntax

After dismissing it, the \*COQTOP\* pane opens but there is no output. I also tried creating a user settings file containing 
```
{
	"coqtop_path": "/usr/local/bin/coqtop"
}
```
but it has no effect. How can I debug this?

**Comment by whitequark** [comment]
How are you installing it?

**Comment by vassilmladenov** [comment]
I used Package Control on a relatively vanilla ST3.

**Comment by whitequark** [comment]
Reproduced, looking into it.
